config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/adminxxx', as: 'rails_admin'
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'customer/registrations',
    sessions: 'customer/sessions'
  }

  #管理者側

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index]
    resources :posts, only: [:index, :edit, :update, :destroy] do
      resources :responses, except: [:index]
    end
    get 'responses/index', to: 'responses#index'
    resources :events, only: [:index, :new, :create, :edit, :update] do
      resources :event_posts, only: [:index]
      get 'event_posts/:id' => 'admin_event_event_posts_path#index'
    end
  end

  #顧客側
  scope module: :customer do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :customers, only: [:edit, :update]
      get 'unsubscribe' => 'customers#unsubscribe'
      patch 'withdraw' => 'customers#withdraw'
    resources :posts, except: [:destroy, :edit, :update]do
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'thanks'
      end
    end
    resources :events, only: [:show] do
      resources :event_posts, only: [:new, :create]
    end
  end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(customer)
    if customer && customer.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :responses, dependent: :destroy
  has_one :event_post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { app: 0, st: 1 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :event_posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :work, presence: true
  validates :access, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin
  has_many :event_posts, dependent: :destroy

 validates :admin_id, presence: true
 validates :title, presence: true
 validates :body, presence: true
 validates :period, presence: true
end

app/models/event_post.rb
class EventPost < ApplicationRecord
  belongs_to :customer
  belongs_to :event

  validates :body, presence: true
  validates :customer_id, presence: true
  validates :event_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  has_one :response
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :category, presence: true
  validates :customer_id, presence: true

end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :admin
  belongs_to :post

  validates :response, presence: true
  validates :post_id, presence: true
  validates :admin_id, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @events = Event.page(params[:page]).reverse_order
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_admin.id
    @event.save
    redirect_to admin_events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to admin_events_path
      flash[:event] = "イベント内容を変更しました！"
    else
      render "edit"
    end
  end

  private
  def event_params
    params.require(:event).permit(:title, :body, :period, :admin_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

   rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_path, alert: "管理者権限がないのでアクセスできません" }
    end
  end

  def after_sign_in_path_for(resource)
      posts_path
  end

  def after_sign_out_path_for(resource)
    posts_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :age, :gender, :work, :access])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact)
          .permit(:email,
                  :name,
                  :phone_number,
                  :subject,
                  :message
                 )
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/event_posts_helper.rb
module Admin::EventPostsHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/responses_helper.rb
module Admin::ResponsesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/posts_helper.rb
module Customer::PostsHelper
end

app/views/admin/events/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <div class="form-group">
      <h4 class="form text-center">イベント情報編集</h4>
      <div class="form-body p-4">
        <%= form_with model:@event, url:admin_event_path do |f| %>
              <%= f.text_field :title, class:"form-control" %>
              <h4></h4>
              <%= f.text_area :body, class:"form-control", size: "20x10" %>
              <h4></h4>
              <%= f.date_select :period, {include_blank: true, start_year: 2022, use_month_numbers: true}, {class: 'time-box'} %>まで
          <div class="post-buttom text-center">
          <%= f.submit "編集を保存する", class:"btn-square-shadow-red" %>
          </div>
        <% end %>
　　　</div>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h3>イベント一覧</h3>
      <% if flash[:event] %>
        <p class="text-active"><%= flash[:event] %></p>
      <% end %>
      <% @events.each do |event| %>
　      <div class="event-card" style="height: 500px;">
        <div class="tape"></div>
        <div class="card-body">
          <h5 class="event-card-title text-center"><%= event.title %></h5>
          <p class="event-card-text" style="height: 200px;"><%= event.body %></p>
          <h6 class="event-card-title text-center"><i class="fas fa-check-circle"></i><%= event.period %>まで</h6>
            <%= link_to "イベントを編集", edit_admin_event_path(event), class: "btn btn-outline-secondary btn-sm btn-block" %></p>
            <%= link_to "このイベントの投稿を見る", admin_event_event_posts_path(event), class: "btn btn-outline-warning btn-sm btn-block" %></p>
        </div>
         </div>
      <% end %>
      <%= paginate @events %>
    </div>
    <div class="col-md-4">
      <h3 class="ivent-title">イベントを作成</h3>
        <div class="event-card" style="height: 550px;">
          <div class="tape"></div>
          <div class="card-body">
          <h5 class="event-card-title text-center">タイトル</h5>
          <p class="event-card-text text-center" style="height: 300px;">内容をここに書きましょう！</p>
            <h6 class="event-card-title text-center"><i class="fas fa-check-circle"></i>〇〇年〇〇月〇〇日まで</h6>
            <%= link_to "イベントを新規作成", new_admin_event_path, class: "btn btn-danger btn-sm btn-block" %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <div class="form-group">
      <h4 class="form text-center">イベント情報作成</h4>
      <% if @event.errors.any? %>
        <%= @event.errors.count %>件のエラーが発生しました
        <% @event.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>
      <div class="form-body p-4">
        <%= form_with model:@event, url:admin_events_path do |f| %>
          <h4></h4>
            <%= f.text_field :title, class:"form-control", placeholder:"見出しを記入してください" %>
          <h4></h4>
            <%= f.text_area :body, class:"form-control", placeholder:"ご意見・ご要望を記入してください", size: "20x10" %>
          <h4></h4>
            <%= f.date_select :period, {include_blank: true, start_year: 2022, use_month_numbers: true}, {class: 'time-box'} %>まで
          <div class="post-buttom text-center">
          <%= f.submit "イベントを作成する", class:"btn-square-shadow-red" %>
          </div>
        <% end %>
　　　</div>
      </div>
    </div>
  </div>
</div>