config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/adminxxx', as: 'rails_admin'
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'customer/registrations',
    sessions: 'customer/sessions'
  }

  #管理者側

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index]
    resources :posts, only: [:index, :edit, :update, :destroy] do
      resources :responses, except: [:index]
    end
    get 'responses/index', to: 'responses#index'
    resources :events, only: [:index, :new, :create, :edit, :update] do
      resources :event_posts, only: [:index]
      get 'event_posts/:id' => 'admin_event_event_posts_path#index'
    end
  end

  #顧客側
  scope module: :customer do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :customers, only: [:edit, :update]
      get 'unsubscribe' => 'customers#unsubscribe'
      patch 'withdraw' => 'customers#withdraw'
    resources :posts, except: [:destroy, :edit, :update]do
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'thanks'
      end
    end
    resources :events, only: [:show] do
      resources :event_posts, only: [:new, :create]
    end
  end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :event_posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :work, presence: true
  validates :access, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  has_one :response
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :category, presence: true
  validates :customer_id, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customer = Customer.page(params[:page]).reverse_order
  end

  def customer_params
    params.require(:customer).permit(:nickname, :age, :gender, :work, :access)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @post = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to posts_path, notice: "会員情報を更新しました！"
    else
      render :edit
    end
  end

  def unsubscribe
    @customer = Customer.find_by(params[:id])
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to posts_path
  end

  private
  def customer_params
    params.require(:customer).permit(:nickname, :age, :gender, :work, :access, :customer_id, :email, :is_deleted)
  end


end

app/controllers/customer/event_posts_controller.rb
class Customer::EventPostsController < ApplicationController
  before_action :authenticate_customer!
  before_action :move_to_signed_in

  def new
    @event_post = EventPost.new
    @event = Event.find(params[:event_id])
  end

  def create
    @event_post = EventPost.new(event_post_params)
    event_id = params[:event_id]
    @event_post.event_id = event_id
    @event_post.customer_id = current_customer.id
    if @event_post.save
      flash[:alert] = "イベントに投稿できました。ありがとうございました！"
      redirect_to posts_path
    else
      render :new
    end
  end

  private
  def move_to_signed_in
    unless customer_signed_in?
      redirect_to new_customer_session_path
    end
  end

  def event_post_params
    params.require(:event_post).permit(:body, :customer_id)
  end

  def event_params
    params.require(:event).permit(:title, :body, :period, :admin_id)
  end

end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    favorite = current_customer.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_customer.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/posts_controller.rb
class Customer::PostsController < ApplicationController
  before_action :authenticate_customer!,except: [:index]

  def index
    @responses = Response.page(params[:page]).reverse_order
    respond_to do |format|
      format.html
      format.js
    end

    @events = Event.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    if @post.save
      redirect_to thanks_posts_path
    else
      render "new"
    end
  end

  def thanks
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category, :customer_id)
  end

end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
    flash[:notice] = "会員登録ができました！"
    posts_path
  end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  before_action :reject_inactive_customer, only: [:create]

    protected

  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    if (@customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == true))
        flash[:danger] = 'お客様は退会済みです。申し訳ございませんが、新規登録をお願いします。'
      redirect_to new_customer_session_path
    end
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/event_posts_helper.rb
module Customer::EventPostsHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/views/customer/posts/_error.html.erb
<section class="inner confirm_error">
	<h2 class="section-ttl">エラー</h2>
	<h6 class="text-center">
		問題が発生しました。<br>
		お手数ですが、再度情報入力からやり直していただきますようお願いします。
	</h6>
	<div class="text-center">
		<%= link_to "注文情報入力に進む", new_order_path, class: "btn btn-success" %>
	</div>
</section>

app/views/customer/posts/_event.html.erb
  <% @events.each do |event| %>
  　<div class="event-card" style="height: 600px;">
      <div class="card-body">
        <h5 class="event-card-title text-center" style="height: 50px;"><%= event.title %></h5>
          <p class="event-card-text" style="height: 400px;"><%= event.body %></p>
          <h6 class="event-card-period text-center"><i class="fas fa-check-circle"></i><%= event.period %>まで</h6>
          <div class="event-post-buttom text-center">
            <%= link_to "投稿", new_event_event_post_path(event), class: "btn-square-shadow " %>
          </div>
      </div>
    </div>
  <% end %>
  <div class="pagination">
    <%= paginate events %>
  </div>

app/views/customer/posts/_index.html.erb
<% responses.each do |response| %>
  <div class="post-card" style="height: 550px;">
    <div id="favorite_buttons_<%= response.post.id %>">
      <%= render 'customer/favorites/favorites', post: response.post %>
    </div>
      <h4 class="post-title">
        <%= response.post.title %>
      </h4>
        <div class="opinion" style="height: 200px;">
        <strong>お客様の投稿</strong>：<i class="fas fa-user"></i><p class="category"><%= response.post.category %></p><br>
        　<%= response.post.body %>
        </div>
        <div class="response" style="height: 200px;">
          <strong>店長からの返答</strong>：<i class="fas fa-user-tie"></i><br>
          <%= response.response %>
      </div>
  </div>
<% end %>
<div class="pagination">
  <%= paginate responses, remote: true %>
</div>

app/views/customer/posts/_index_response.html.erb
<% responses.each do |response| %>
  <div class="post-card" style="height: 550px;">
    <div id="favorite_buttons_<%= response.post.id %>">
      <%= render 'customer/favorites/favorites', post: response.post %>
    </div>
      <h4 class="post-title">
        <%= response.post.title %>
      </h4>
      <div class="opinion" style="height: 200px;">
        <strong>お客様の投稿</strong>：<i class="fas fa-user"></i><p class="category"><%= response.post.category %></p><br>
        　<%= response.post.body %>
      </div>
      <div class="response" style="height: 200px;">
        <strong>店長からの返答</strong>：<i class="fas fa-user-tie"></i><br>
        <%= response.response %>
      </div>
  </div>
<% end %>
<div class="pagination">
  <%= paginate responses, remote: true %>
</div>

app/views/customer/posts/index.html.erb
<div class="container">
  <div class="text-center">
    <div class="pricing-header text-center">
      <div class="display-3 fw-normal">
        <div class="row">
          <%= image_tag('top.right.jpg') %>
          <%= image_tag('top.head1.png') %>
          <%= image_tag('top.left.jpg') %>
        </div>
      </div>
              <h2>安心・新鮮・おいしさ</h2>
    </div>
    <% if flash[:notice] %>
      <p class="text-active"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="text-active"><%= flash[:alert] %></p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-7">
      <h3>お客様の声一覧</h3>
      <div id="response-pagenate">
        <%= render 'index_response', responses: @responses %>
      </div>
    </div>
    <div class="col-md-5">
      <h3 class="ivent-title">イベント情報</h3>
        <%= render 'event', events: @events %>
    </div>
  </div>
</div>

app/views/customer/posts/index.js.erb
 $('#response-pagenate').html("<%= escape_javascript(render 'index_response', responses: @responses) %>");

app/views/customer/posts/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-sm-auto shadow-lg rounded px-0 my-5">
      <div class="form-group">
      <h4 class="form text-center">投稿する</h4>
        <div class="text-center">
          <% if @post.errors.any? %>
            <%= @post.errors.count %>件のエラーが発生しました。<br>
            <% @post.errors.full_messages.each do |message| %>
            <%= message %>
            <% end %>
          <% end %>
        </div>
      <div class="form-body p-4">
        <%= form_with model:@post, local: true do |f| %>
              <h4></h4>
              <%= f.select :category, ['商品', 'サービス', '設備', 'その他'], { include_blank: 'カテゴリーを選択してください'}, { class: 'form-control' , required: true }%>
              <h4></h4>
              <%= f.text_field :title, class:"form-control", placeholder:"見出しを記入してください" %>
              <h4></h4>
              <%= f.text_area :body, class:"form-control", placeholder:"ご意見・ご要望を記入してください", size: "20x10" %>
          <div class="post-buttom text-center">
          <%= f.submit "送信", class:"btn-square-shadow-red" %>
          </div>
        <% end %>
　　　</div>
      </div>
    </div>
  </div>
</div>

app/views/customer/posts/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row">
    <div class="col-md-8">
      <h3 class="text-center">お客様の声</h3>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th><%= @post.category %></th>
            </tr>
            <tr>
              <th><%= @post.title %></th>
            </tr>
          </thead>
          <tbody>
          <tr>
            <td><%= @post.body %></td>
          </tr>
          <tr>
          　<td><%#= @response.response %></td>
          </tr>
          </tbody>
        </table>
  	</div>
  	  <div class="col-md-4">
      	<h3 class="text-center">イベント情報</h3>
        <h5><%#= event_post.title %></h5>
        <h5><%#= event_post.body %></td>
        <%#= link_to "編集する", edit_admin_event_post_path, class: "btn btn-secondary" %>
      </div>
  </div>
</div>

app/views/customer/posts/thanks.html.erb
<div class="container">
  <div class="thanks">
    <p class="thankyou text-center">
      投稿完了しました！<br>
      ありがとうございます。
    </p>
    <h4 class="text-center">店長からの返事が完了すると<br>
        投稿一覧ページにて掲載いたします。
    </h4>
  </div>
</div>